title: Encryption
docker:
  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
    properties:
      bootstrap.server: localhost:29092
  gateway:
    image: ghcr.io/conduktor/conduktor-gateway-distro
    environment:
      GATEWAY_SECURITY_PROTOCOL: SASL_PLAINTEXT
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"franklx\" password=\"eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImZyYW5rbHgiLCJ2Y2x1c3RlciI6ImZyYW5rbHgiLCJleHAiOjExNjkyMDg4MjI0fQ.RaDEBfXwUJHKYiDeOGQ8HgLT7K9yCnNa6SckSvHZuCw\";"
      bootstrap.servers: localhost:6969
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto.offset.reset: earliest
      enable.auto.commit: false
      client.id: clientId
plugins:
  franklx:
    encryption-interceptor-config:
      pluginClass: "io.conduktor.gateway.interceptor.EncryptPlugin"
      "priority": 1
      "config": {
        "topic": "encryptedTopic",
        "schemaRegistryConfig": {
          "host": "http://schema-registry:8081"
        },
        "fields": [
          {
            "fieldName": "password",
            "keySecretId": "secret-key-password",
            "algorithm": {
              "type": "AES_GCM",
              "kms": "IN_MEMORY"
            }
          },
          {
            "fieldName": "visa",
            "keySecretId": "secret-key-visaNumber",
            "algorithm": {
              "type": "AES_GCM",
              "kms": "IN_MEMORY"
            }
          }
        ]
      }
    decryption-interceptor-config:
      pluginClass: "io.conduktor.gateway.interceptor.DecryptPlugin"
      "priority": 1
      "config": {
        "topic": "encryptedTopic",
        "schemaRegistryConfig": {
          "host": "http://schema-registry:8081"
        }
      }
actions:
  - type: CREATE_TOPIC
    target: GATEWAY
    topic: encryptedTopic
  - type: PRODUCE
    target: GATEWAY
    topic: encryptedTopic
    messages:
      - value: '{"name":"conduktor","username":"test@conduktor.io","password":"password1","visa":"visa123456","address":"Conduktor Towers, London"}'
  - type: FETCH
    target: GATEWAY
    topic: encryptedTopic
    assertions:
      - description: confirm decryption at gateway
        value:
          operator: isEqualTo
          expected: '{"name":"conduktor","username":"test@conduktor.io","password":"password1","visa":"visa123456","address":"Conduktor Towers, London"}'
  - type: FETCH
    target: KAFKA
    topic: franklxencryptedTopic
    assertions:
      - description: confirm encryption at rest - only 2 fields password and visa are encrypted
        value:
          operator: satisfies
          expected: '[name] == "conduktor" && [username] == "test@conduktor.io" && [password] != "password1" && [visa] != "visa123456" && [address] == "Conduktor Towers, London"'
