title: Simple test with NONE authenticator type
docker:
  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
    properties:
      bootstrap.servers: localhost:29092,localhost:29093
      auto.offset.reset: earliest
      enable.auto.commit: false
      client.id: clientId
  gateway:
    image: ghcr.io/conduktor/conduktor-gateway-distro
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9093
      GATEWAY_ADVERTISED_HOST: localhost
      GATEWAY_SECURITY_PROTOCOL: SASL_PLAINTEXT
      GATEWAY_FEATURE_FLAGS_MULTI_TENANCY: true
    properties:
      bootstrap.servers: localhost:6969
      auto.offset.reset: earliest
      enable.auto.commit: false
      client.id: clientId
actions:

  - type: CREATE_VIRTUAL_CLUSTERS
    gateway: gateway
    names:
      - gateway
      - teamA

  - type: DESCRIBE_KAFKA_PROPERTIES
    kafka: teamA
    assertKeys:
      - bootstrap.servers

  - type: CREATE_TOPICS
    kafka: teamA
    topics:
      - name: encryptedTopic
        replicationFactor: 1
        partitions: 1

  - type: LIST_TOPICS
    kafka: teamA
    assertDoesNotExist:
      - blabla123
    assertExists:
      - encryptedTopic

  - type: PRODUCE
    kafka: teamA
    topic: encryptedTopic
    messages:
      - value: '{"msg": "hello world"}'

  - type: CONSUME
    kafka: teamA
    properties:
      group.id: consume-hello
      auto.offset.reset: earliest
    topics:
      - encryptedTopic
    assertSize: 1
    assertions:
      - description: confirm hello is back
        value:
          operator: containsIgnoreCase
          expected: 'hello world'
      - description: confirm blabla does not exists
        value:
          operator: doesNotContainIgnoringCase
          expected: 'blabla'

  - type: DESCRIBE_TOPICS
    kafka: teamA
    topics:
      - encryptedTopic
    assertions:
      - name: encryptedTopic
        replicationFactor: 1
        partitions: 1

  - type: ADD_INTERCEPTORS
    gateway: gateway
    interceptors:
      teamA:
        encryption:
          pluginClass: "io.conduktor.gateway.interceptor.EncryptPlugin"
          "priority": 1
          "config": {
            "topic": "encryptedTopic",
            "schemaRegistryConfig": {
              "host": "http://schema-registry:8081"
            },
            "fields": [
              {
                "fieldName": "password",
                "keySecretId": "secret-key-password",
                "algorithm": {
                  "type": "AES_GCM",
                  "kms": "IN_MEMORY"
                }
              },
              {
                "fieldName": "visa",
                "keySecretId": "secret-key-visaNumber",
                "algorithm": {
                  "type": "AES_GCM",
                  "kms": "IN_MEMORY"
                }
              }
            ]
          }

  - type: LIST_INTERCEPTORS
    gateway: gateway
    vcluster: teamA
    assertSize: 1
    assertNames:
      - encryption

  - type: PRODUCE
    kafka: teamA
    topic: encryptedTopic
    messages:
      - value: '{"name":"conduktor","username":"test@conduktor.io","password":"password1","visa":"visa123456","address":"Conduktor Towers, London"}'

  - type: CONSUME
    kafka: teamA
    topics:
      - encryptedTopic
    properties:
      group.id: consume-after-encryption
      auto.offset.reset: earliest
    assertSize: 2
    assertions:
      - description: confirm hello is back
        value:
          operator: containsIgnoreCase
          expected: 'hello world'
      - description: confirm password does not exists
        value:
          operator: doesNotContainIgnoringCase
          expected: 'password1'
      - description: confirm encryption at rest - only 2 fields password and visa are encrypted
        value:
          operator: satisfies
          expected: '[name] == "conduktor" && [username] == "test@conduktor.io" && [password] != "password1" && [visa] != "visa123456" && [address] == "Conduktor Towers, London"'

  - type: REMOVE_INTERCEPTORS
    gateway: gateway
    vcluster: teamA
    names:
      - encryption

  - type: LIST_INTERCEPTORS
    gateway: gateway
    vcluster: teamA
    assertSize: 0

  - type: STEP
    description: Step1

  - type: DOCUMENTATION
    description: blabla

  - type: MARKDOWN
    markdown: |
      Run the full setup 

      ```bash
      docker compose up --wait --detach
      ```

      Run the demo

      ```sh
      ./run.sh
      ```

  - type: BASH
    script: echo 'hello'
    assertOutputContains:
      -  hello
    assertOutputDoesNotContain:
      -  blabla

  - type: SH
    script: >
      echo 'glou'; 
      exit 3;
    assertExitCode: 3
    assertOutputContains:
      -  glou
    assertOutputDoesNotContain:
      -  blabla

  - type: SUCCESS
