title: Simple test with NONE authenticator type
docker:
  kafka:
    version: latest
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
  gateway:
    version: 2.0.0-amd64
    environment:
      GATEWAY_SECURITY_PROTOCOL: NONE
      GATEWAY_FEATURE_FLAGS_MULTI_TENANCY: "false"
actions:
  - type: CREATE_TOPIC
    target: GATEWAY
    topic: topic1
  - type: PRODUCE
    target: GATEWAY
    topic: topic1
    messages:
      - key: "key1"
        value: "value1"
        headers:
          header_key1: "headerValue1"
          header_key2: "headerValue2"
      - key: "key2"
        value: "value2"
        headers:
          header_key3: "headerValue3"
          header_key4: "headerValue4"
  - type: FETCH
    target: KAFKA
    topic: topic1
    assertions:
      - key:
          expected: "key1"
        value:
          expected: "value1"
        headers:
          header_key1:
            expected: "headerValue1"
          header_key2:
            expected: "headerValue2"
      - key:
          expected: "key2"
        value:
          expected: "value2"
        headers:
          header_key3:
            expected: "headerValue3"
          header_key4:
            expected: "headerValue4"
  - type: FETCH
    target: GATEWAY
    topic: topic1
    assertions:
      - key:
          expected: "key1"
        value:
          expected: "value1"
        headers:
          header_key1:
            expected: "headerValue1"
          header_key2:
            expected: "headerValue2"
      - key:
          expected: "key2"
        value:
          expected: "value2"
        headers:
          header_key3:
            expected: "headerValue3"
          header_key4:
            expected: "headerValue4"