kafka:
  version: latest
  environment:
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
gateway:
  version: 1.8.2.12-amd64
  environment:
    AUTHENTICATION_AUTHENTICATOR_TYPE: NONE
plugins:
workflow:
  gatewayRequest: '{
                "key": "message2_key",
                "value": "Hello, Kafka! This is message 2.",
                "headers": [
                  ("header_key3", "header_value3"),
                  ("header_key4", "header_value4")
                ]
            }'
  kafkaResponse: '{
              "key": "message2_key",
              "value": "Hello, Kafka! This is message 2.",
              "headers": [
                ("header_key3", "header_value3"),
                ("header_key4", "header_value4")
              ]
          }'
  gatewayResponse: '{
              "key": "message2_key",
              "value": "Hello, Kafka! This is message 2.",
              "headers": [
                ("header_key3", "header_value3"),
                ("header_key4", "header_value4")
              ]
          }'