title: Simple test with NONE authenticator type
docker:
  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
    properties:
      bootstrap.servers: localhost:29092,localhost:29093
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto.offset.reset: earliest
      enable.auto.commit: false
      client.id: clientId
  gateway:
    image: ghcr.io/conduktor/conduktor-gateway-distro
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9093
      GATEWAY_ADVERTISED_HOST: localhost
      GATEWAY_SECURITY_PROTOCOL: NONE
    properties:
      bootstrap.servers: localhost:6969
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto.offset.reset: earliest
      enable.auto.commit: false
      client.id: clientId
actions:
  - type: STEP
    description: Step1
  - type: DOCUMENTATION
    description: blabla
  - type: CREATE_TOPICS
    target: GATEWAY
    topics:
      - name: encryptedTopic
        replicationFactor: 1
        partitions: 1
  - type: ADD_INTERCEPTORS
    target: GATEWAY
    interceptors:
      clusterA:
        encryption-interceptor-config:
          pluginClass: "io.conduktor.gateway.interceptor.EncryptPlugin"
          "priority": 1
          "config": {
            "topic": "encryptedTopic",
            "schemaRegistryConfig": {
              "host": "http://schema-registry:8081"
            },
            "fields": [
              {
                "fieldName": "password",
                "keySecretId": "secret-key-password",
                "algorithm": {
                  "type": "AES_GCM",
                  "kms": "IN_MEMORY"
                }
              },
              {
                "fieldName": "visa",
                "keySecretId": "secret-key-visaNumber",
                "algorithm": {
                  "type": "AES_GCM",
                  "kms": "IN_MEMORY"
                }
              }
            ]
          }
  - type: LIST_INTERCEPTORS
    target: GATEWAY
    vcluster: clusterA
    assertSize: 1
    assertNames:
      - encryption-interceptor-config
  - type: REMOVE_INTERCEPTORS
    target: GATEWAY
    vcluster: clusterA
    names:
      - encryption-interceptor-config
  - type: LIST_INTERCEPTORS
    target: GATEWAY
    vcluster: clusterA
    assertSize: 0
