title: Simple test with NONE authenticator type
docker:
  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
    properties:
      bootstrap.servers: localhost:29092,localhost:29093
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto.offset.reset: earliest
      enable.auto.commit: false
      client.id: clientId
  gateway:
    image: ghcr.io/conduktor/conduktor-gateway-distro
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9093
      GATEWAY_ADVERTISED_HOST: localhost
      GATEWAY_SECURITY_PROTOCOL: NONE
    properties:
      bootstrap.servers: localhost:6969
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto.offset.reset: earliest
      enable.auto.commit: false
      client.id: clientId
actions:
  - type: CREATE_TOPIC
    target: GATEWAY
    topic: topic1
  - type: PRODUCE
    target: GATEWAY
    topic: topic1
    messages:
      - key: "key1"
        value: "value1"
        headers:
          header_key1: "headerValue1"
          header_key2: "headerValue2"
      - key: "key2"
        value: "value2"
        headers:
          header_key3: "headerValue3"
          header_key4: "headerValue4"
  - type: FETCH
    target: KAFKA
    topic: topic1
    assertions:
      - key:
          expected: "key1"
        value:
          expected: "value1"
        headers:
          header_key1:
            expected: "headerValue1"
          header_key2:
            expected: "headerValue2"
      - key:
          expected: "key2"
        value:
          expected: "value2"
        headers:
          header_key3:
            expected: "headerValue3"
          header_key4:
            expected: "headerValue4"
  - type: FETCH
    target: GATEWAY
    topic: topic1
    assertions:
      - key:
          expected: "key1"
        value:
          expected: "value1"
        headers:
          header_key1:
            expected: "headerValue1"
          header_key2:
            expected: "headerValue2"
      - key:
          expected: "key2"
        value:
          expected: "value2"
        headers:
          header_key3:
            expected: "headerValue3"
          header_key4:
            expected: "headerValue4"