title: Simple test with SSL
docker:
  kafka:
    version: latest
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
  gateway:
    version: 2.0.0-amd64
    environment:
      GATEWAY_SECURITY_PROTOCOL: SSL
actions:
  - type: CREATE_TOPIC
    target: GATEWAY
    properties:
      security.protocol: SSL
      sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"franklx\" password=\"eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImZyYW5rbHgiLCJ2Y2x1c3RlciI6ImZyYW5rbHgiLCJleHAiOjExNjkyMDg4MjI0fQ.RaDEBfXwUJHKYiDeOGQ8HgLT7K9yCnNa6SckSvHZuCw\";"
    topic: topic1
  - type: PRODUCE
    target: GATEWAY
    properties:
      security.protocol: SSL
      sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"franklx\" password=\"eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImZyYW5rbHgiLCJ2Y2x1c3RlciI6ImZyYW5rbHgiLCJleHAiOjExNjkyMDg4MjI0fQ.RaDEBfXwUJHKYiDeOGQ8HgLT7K9yCnNa6SckSvHZuCw\";"
    topic: topic1
    messages:
      - key: "key3"
        value: "value3"
        headers:
          header_key1: "headerValue5"
          header_key2: "headerValue5"
  - type: FETCH
    target: GATEWAY
    properties:
      security.protocol: SSL
      sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"franklx\" password=\"eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImZyYW5rbHgiLCJ2Y2x1c3RlciI6ImZyYW5rbHgiLCJleHAiOjExNjkyMDg4MjI0fQ.RaDEBfXwUJHKYiDeOGQ8HgLT7K9yCnNa6SckSvHZuCw\";"
    topic: topic1
    assertions:
      - key:
          expected: "key3"
        value:
          expected: "value3"
        headers:
          header_key1:
            expected: "headerValue5"
          header_key2:
            expected: "headerValue5"