kafka:
  version: latest
  environment:
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
gateway:
  version: 1.8.2.12-amd64
  environment:
    AUTHENTICATION_AUTHENTICATOR_TYPE: NONE
plugins:
io:
  input:
    key: "key3"
    value: "value3"
    headers:
      header_key1: "headerValue5"
      header_key2: "headerValue5"
  output:
    key: "key3"
    value: "value3"
    headers:
      header_key1: "headerValue5"
      header_key2: "headerValue5"