title: Simple test with SSL
docker:
  kafka:
    version: latest
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
  gateway:
    version: 2.0.0.alpha
    environment:
      GATEWAY_SECURITY_PROTOCOL: SSL
actions:
  - type: CREATE_TOPIC
    target: GATEWAY
    properties:
      security.protocol: SSL
      sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"franklx\" password=\"eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImZyYW5rbHgiLCJ0ZW5hbnQiOiJmcmFua2x4IiwiZXhwIjoxMTY5MDkwOTQ1Nn0.eDsobtVTFg2Rciy-y7x7GxqdzuEb9ZStWih9P9VuSzE\";"
    topic: topic1
  - type: PRODUCE
    target: GATEWAY
    properties:
      security.protocol: SSL
      sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"franklx\" password=\"eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImZyYW5rbHgiLCJ0ZW5hbnQiOiJmcmFua2x4IiwiZXhwIjoxMTY5MDkwOTQ1Nn0.eDsobtVTFg2Rciy-y7x7GxqdzuEb9ZStWih9P9VuSzE\";"
    topic: topic1
    messages:
      - key: "key3"
        value: "value3"
        headers:
          header_key1: "headerValue5"
          header_key2: "headerValue5"
  - type: FETCH
    target: GATEWAY
    properties:
      security.protocol: SSL
      sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"franklx\" password=\"eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImZyYW5rbHgiLCJ0ZW5hbnQiOiJmcmFua2x4IiwiZXhwIjoxMTY5MDkwOTQ1Nn0.eDsobtVTFg2Rciy-y7x7GxqdzuEb9ZStWih9P9VuSzE\";"
    topic: topic1
    messages:
      - key: "key3"
        value: "value3"
        headers:
          header_key1: "headerValue5"
          header_key2: "headerValue5"