title: Virtual SQL with Avro
services:
  kafka1:
    properties:
      bootstrap.servers: localhost:29092,localhost:29093,localhost:29094
      auto.offset.reset: earliest
      enable.auto.commit: false
      client.id: clientId
  kafka2:
    properties:
      bootstrap.servers: localhost:29092,localhost:29093,localhost:29094
      auto.offset.reset: earliest
      enable.auto.commit: false
      client.id: clientId
  kafka3:
    properties:
      bootstrap.servers: localhost:29092,localhost:29093,localhost:29094
      auto.offset.reset: earliest
      enable.auto.commit: false
      client.id: clientId
  gateway:
    docker:
      image: ghcr.io/conduktor/conduktor-gateway-distro
      environment:
        GATEWAY_ADVERTISED_HOST: localhost
        GATEWAY_SECURITY_PROTOCOL: SASL_PLAINTEXT
        GATEWAY_FEATURE_FLAGS_MULTI_TENANCY: true
    properties:
      bootstrap.servers: localhost:6969
      auto.offset.reset: earliest
      enable.auto.commit: false
      client.id: clientId
actions:

  - type: CREATE_VIRTUAL_CLUSTERS
    gateway: gateway
    names:
      - teamA

  - type: CREATE_TOPICS
    kafka: teamA
    topics:
      - name: cars
        replicationFactor: 1
        partitions: 1

  - type: LIST_TOPICS
    kafka: teamA
    assertExists:
      - cars

  - type: BASH
    kafka: teamA
    showOutput: true
    script: |
      PATH=$PATH:/Users/framiere/confluent-7.4.1/bin
      echo '{"type":"Sports","price":75,"color":"blue"}' | \
          kafka-avro-console-producer  \
              --bootstrap-server bootstrap.servers=${BOOTSTRAP_SERVERS} \
              --producer.config teamA.properties \
              --topic cars \
              --property schema.registry.url=http://localhost:8081 \
              --property value.schema='{
                  "type": "record",
                  "name": "car",
                  "fields": [
                    {"name": "type", "type": "string"},
                    {"name": "price", "type": "long"},
                    {"name": "color", "type": "string"}
                  ]
                }'
      
      echo '{"type":"SUV","price":55,"color":"red"}' | \
          kafka-avro-console-producer  \
              --bootstrap-server bootstrap.servers=${BOOTSTRAP_SERVERS} \
              --producer.config teamA.properties \
              --topic cars \
              --property schema.registry.url=http://localhost:8081 \
              --property value.schema='{
                  "type": "record",
                  "name": "car",
                  "fields": [
                    {"name": "type", "type": "string"},
                    {"name": "price", "type": "long"},
                    {"name": "color", "type": "string"}
                  ]
                }'
      
  - type: BASH
    kafka: teamA
    showOutput: true
    script: |
      PATH=$PATH:/Users/framiere/confluent-7.4.1/bin
      kafka-avro-console-consumer  \
          --bootstrap-server bootstrap.servers=${BOOTSTRAP_SERVERS} \
          --consumer.config teamA.properties \
          --topic cars \
          --property schema.registry.url=http://localhost:8081 \
          --from-beginning \
          --max-messages 2

  - type: CREATE_TOPICS
    kafka: teamA
    topics:
      - name: red-cars
        replicationFactor: 1
        partitions: 1

  - type: ADD_INTERCEPTORS
    gateway: gateway
    interceptors:
      teamA:
        red-cars:
          "pluginClass": "io.conduktor.gateway.interceptor.VirtualSqlTopicPlugin"
          "priority": "100"
          "config": {
            "virtualTopic": "red-cars",
            "statement": "SELECT * FROM cars WHERE color = 'red'",
            "schemaRegistryConfig": {
              "host": "http://schema-registry:8081"
            }
          }

  - type: LIST_INTERCEPTORS
    gateway: gateway
    vcluster: teamA
    assertSize: 1
    assertNames:
      - red-cars

  - type: BASH
    kafka: teamA
    showOutput: true
    script: |
      PATH=$PATH:/Users/framiere/confluent-7.4.1/bin
      kafka-avro-console-consumer  \
          --bootstrap-server bootstrap.servers=${BOOTSTRAP_SERVERS} \
          --consumer.config teamA.properties \
          --topic red-cars \
          --property schema.registry.url=http://localhost:8081 \
          --from-beginning \
          --max-messages 1 | grep "{" | jq
    assertOutputDoesNotContain:
      - blue
    assertOutputContains:
      - Processed a total of 1 messages
      - red

  - type: SUCCESS
