title: Virtual SQL with Avro
services:
  kafka1:
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
    properties:
      bootstrap.servers: localhost:29092,localhost:29093,localhost:29094
  kafka2:
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
    properties:
      bootstrap.servers: localhost:29092,localhost:29093,localhost:29094
  kafka3:
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
    properties:
      bootstrap.servers: localhost:29092,localhost:29093,localhost:29094
  gateway1:
    docker:
      environment:
        GATEWAY_ADVERTISED_HOST: localhost
        GATEWAY_SECURITY_PROTOCOL: SASL_PLAINTEXT
        GATEWAY_FEATURE_FLAGS_MULTI_TENANCY: true
    properties:
      bootstrap.servers: localhost:6969
      gateway.host: http://localhost:8888
  gateway2:
    docker:
      environment:
        GATEWAY_ADVERTISED_HOST: localhost
        GATEWAY_SECURITY_PROTOCOL: SASL_PLAINTEXT
        GATEWAY_FEATURE_FLAGS_MULTI_TENANCY: true
    properties:
      bootstrap.servers: localhost:6969
      gateway.host: http://localhost:8889

actions:
  - type: INTRODUCTION
    title: Yes, SQL topic work with Avro/ProtoBuff.

  - type: ASCIINEMA

  - type: FILE
    title: Review the docker compose environment
    filename: docker-compose.yaml
    markdown: |
      As can be seen from `docker-compose.yaml` the demo environment consists of the following:
      
      * A single Zookeeper Server
      * A main 3 nodes Kafka cluster
      * A 2 nodes Conduktor Gateway server

  - type: DOCKER
    title: Start the docker environment
    command: docker compose up -d --wait
    markdown: Start your docker environment

  - type: CREATE_VIRTUAL_CLUSTERS
    gateway: gateway1
    name: teamA

  - type: CREATE_TOPICS
    kafka: teamA
    kafkaConfig: teamA-sa.properties
    topics:
      - name: cars
        replicationFactor: 1
        partitions: 1

  - type: LIST_TOPICS
    kafka: teamA
    kafkaConfig: teamA-sa.properties
    assertExists:
      - cars

  - type: SH
    title: Produce avro payload
    kafka: teamA
    kafkaConfig: teamA-sa.properties
    showOutput: true
    script: |
      schema='{
                  "type": "record",
                  "name": "car",
                  "fields": [
                    {"name": "type", "type": "string"},
                    {"name": "price", "type": "long"},
                    {"name": "color", "type": "string"}
                  ]
                }'
      echo '{"type":"Sports","price":75,"color":"blue"}' | \
          kafka-avro-console-producer  \
              --bootstrap-server ${BOOTSTRAP_SERVERS} \
              --producer.config ${KAFKA_CONFIG_FILE} \
              --topic cars \
              --property schema.registry.url=http://localhost:8081 \
              --property "value.schema=$schema"
      
      echo '{"type":"SUV","price":55,"color":"red"}' | \
          kafka-avro-console-producer  \
              --bootstrap-server ${BOOTSTRAP_SERVERS} \
              --producer.config ${KAFKA_CONFIG_FILE} \
              --topic cars \
              --property schema.registry.url=http://localhost:8081 \
              --property "value.schema=$schema"
      
  - type: SH
    title: Consume the avro payload back
    kafka: teamA
    kafkaConfig: teamA-sa.properties
    showOutput: true
    script: |
      kafka-avro-console-consumer  \
          --bootstrap-server ${BOOTSTRAP_SERVERS} \
          --consumer.config ${KAFKA_CONFIG_FILE} \
          --topic cars \
          --property schema.registry.url=http://localhost:8081 \
          --from-beginning \
          --max-messages 2 2>&1 | grep "{" | jq

  - type: CREATE_TOPICS
    kafka: teamA
    kafkaConfig: teamA-sa.properties
    topics:
      - name: red-cars
        replicationFactor: 1
        partitions: 1

  - type: ADD_INTERCEPTORS
    title: Creating the `red-cars` sql interceptor
    gateway: gateway1
    interceptors:
      teamA:
        red-cars:
          "pluginClass": "io.conduktor.gateway.interceptor.VirtualSqlTopicPlugin"
          "priority": "100"
          "config": {
            "virtualTopic": "red-cars",
            "statement": "SELECT * FROM cars WHERE color = 'red'",
            "schemaRegistryConfig": {
              "host": "http://schema-registry:8081"
            }
          }

  - type: LIST_INTERCEPTORS
    gateway: gateway1
    vcluster: teamA
    assertSize: 1
    assertNames:
      - red-cars

  - type: SH
    title: Read from the `red-cars` topic
    kafka: teamA
    kafkaConfig: teamA-sa.properties
    showOutput: true
    script: |
      kafka-avro-console-consumer  \
          --bootstrap-server ${BOOTSTRAP_SERVERS} \
          --consumer.config ${KAFKA_CONFIG_FILE} \
          --topic red-cars \
          --property schema.registry.url=http://localhost:8081 \
          --from-beginning \
          --max-messages 1 2>&1 | grep "{" | jq
    assertOutputDoesNotContain:
      - blue
    assertOutputContains:
      - Processed a total of 1 messages
      - red

  - type: DOCKER
    title: Cleanup the docker environment
    command: docker compose down -v
    markdown: Remove all components from docker

  - type: CONCLUSION
    markdown: |
      SQL virtual topics can also work on data serialized with Schema Registry!
