title: Schema Id validation
services:
  kafka1:
    properties:
      bootstrap.servers: localhost:29092,localhost:29093,localhost:29094
      auto.offset.reset: earliest
      enable.auto.commit: false
      client.id: clientId
  kafka2:
    properties:
      bootstrap.servers: localhost:29092,localhost:29093,localhost:29094
      auto.offset.reset: earliest
      enable.auto.commit: false
      client.id: clientId
  kafka3:
    properties:
      bootstrap.servers: localhost:29092,localhost:29093,localhost:29094
      auto.offset.reset: earliest
      enable.auto.commit: false
      client.id: clientId
  gateway1:
    docker:
      environment:
        GATEWAY_ADVERTISED_HOST: localhost
        GATEWAY_SECURITY_PROTOCOL: SASL_PLAINTEXT
        GATEWAY_FEATURE_FLAGS_MULTI_TENANCY: true
    properties:
      bootstrap.servers: localhost:6969,localhost:7969
      auto.offset.reset: earliest
      enable.auto.commit: false
      client.id: clientId
  gateway2:
    docker:
      environment:
        GATEWAY_ADVERTISED_HOST: localhost
        GATEWAY_SECURITY_PROTOCOL: SASL_PLAINTEXT
        GATEWAY_FEATURE_FLAGS_MULTI_TENANCY: true
    properties:
      bootstrap.servers: localhost:6969,localhost:7969
      auto.offset.reset: earliest
      enable.auto.commit: false
      client.id: clientId
actions:

  - type: CREATE_VIRTUAL_CLUSTERS
    gateway: gateway1
    names:
      - teamA

  - type: CREATE_TOPICS
    kafka: teamA
    topics:
      - name: users
        replicationFactor: 1
        partitions: 1

  - type: LIST_TOPICS
    kafka: teamA
    assertExists:
      - users

  - type: ADD_INTERCEPTORS
    gateway: gateway1
    interceptors:
      teamA:
        schema-id:
          "pluginClass": "io.conduktor.gateway.interceptor.safeguard.TopicRequiredSchemaIdPolicyPlugin"
          "priority": 100
          "config": {
            "topic": "users",
            "schemaIdRequired": true
          }

  - type: LIST_INTERCEPTORS
    gateway: gateway1
    vcluster: teamA
    assertSize: 1
    assertNames:
      - schema-id

  - type: PRODUCE
    kafka: teamA
    topic: users
    assertError: true
    assertErrorMessages:
      -  Request parameters do not satisfy the configured policy. Topic 'users' with schemaId is required.
    messages:
      - value: '{"msg":"hello world"}'

  - type: CONSUME
    kafka: teamA
    properties:
      group.id: consume-should-be-empty
      auto.offset.reset: earliest
    topics:
      - users
    assertSize: 0

  - type: SH
    kafka: teamA
    showOutput: true
    script: |
      PATH=$PATH:/Users/framiere/confluent-7.4.1/bin
      echo '{
          "name": "conduktor",
          "username": "test@conduktor.io",
          "password": "password1",
          "visa": "visa123456",
          "address": "Conduktor Towers, London"
      }' | jq -c | kafka-json-schema-console-producer  \
              --bootstrap-server ${BOOTSTRAP_SERVERS} \
              --producer.config teamA.properties \
              --topic users \
              --property schema.registry.url=http://localhost:8081 \
              --property value.schema='{
                  "title": "User",
                  "type": "object",
                  "properties": {
                      "name": { "type": "string" },
                      "username": { "type": "string" },
                      "password": { "type": "string" },
                      "visa": { "type": "string" },
                      "address": { "type": "string" }
                  }
              }'
     
  - type: SH
    kafka: teamA
    showOutput: true
    script: |
      curl --silent http://localhost:8081/subjects/ | jq     

  - type: CONSUME
    kafka: teamA
    properties:
      group.id: consume-users
      auto.offset.reset: earliest
    topics:
      - users
    assertSize: 1

  - type: SUCCESS
